### ISSUE TITLE
Compatibility with 3dCanvas

### ISSUE THREAD

**Issue by surrealzerg** [Saibot393/LocknKey#133]
When using 3dCanvas (TheRipper93), the module does not function as expected. A lock created with a given ID does not open when a player with a matching key ID interacts with the door. The tile is configured as a door and initially in the locked state.

**Comment by Saibot393** [comment]
I will look into it, might take a bit though, i am not that familiar with 3d Canvas

**Comment by surrealzerg** [comment]
These are tile properties related to a tile's door state in 3d Canvas.

await doorTile.update({ 
    "flags.levels-3d-preview.doorState": 1 // 
});

0 = closed
1 = open
2 = locked

**Comment by Saibot393** [comment]
Thank you, i will try to add it in the next update

**Comment by surrealzerg** [comment]
I looked into this for a couple hours yesterday. I didn't make as much progress as I'd hoped, but after reading through the code base, it looks like you handle compatibility with other modules through LnKCompatibility.js and LnKCompUtils.js. I made updates to those files to align with the current code structure. But I'm still not getting any code execution as I don't believe that toggleLock() is getting called.

Any help appreciated.

**Comment by Saibot393** [comment]
I am so sorry, i completely forgot about this. I will start looking for an implementation immediatly

**Comment by Saibot393** [comment]
As a quick update, i am almost done, there is just one small bug that i have yet to solve and a few test that i want to run.

**Comment by surrealzerg** [comment]
Thanks so much for looking into this!

**Comment by Saibot393** [comment]
With v4.1.0 Lock & Key should now be compatible with 3D Canvas

**Comment by surrealzerg** [comment]
I did some testing on 4.1.0 and identified an issue.
When Lock&Key is enabled, door locked or unlocked in Lock&Key, it's no longer possible to update any of the settings under 3D -> Vision. 
Tile.locked is set to false.

**Comment by Saibot393** [comment]
Sorry for that, should now be fixed with v4.1.1

**Comment by surrealzerg** [comment]
Looks like we fixed that issue but re-opened the initial issue.
Players can no longer open doors using keys.
Confirmed that you can now modify the settings under 3D > Vision when a tile is set as Locked under Lock&Key settings.

**Comment by Saibot393** [comment]
Regarding the Keys, everything seems to work as expected for me, a few questions:
- Are there any errors in the console when using the key?
- Could you try regenerating the key, in case a lock & key setting somehow reset?

**Comment by surrealzerg** [comment]
I recreated the key, but I'm still experiencing the issue. Doors with a given key ID don't unlock when a player has the item with a matching key ID.
Here's my tile and item settings:
![Image](https://github.com/user-attachments/assets/527204b1-f77c-454e-b4a1-642c4e798244)

![Image](https://github.com/user-attachments/assets/6896f0e6-7af4-4958-b269-32b1cbb5151c)

![Image](https://github.com/user-attachments/assets/68ed1ece-20e5-4985-960e-247f107fc299)

**Comment by Saibot393** [comment]
I will do a few more tests. It worked with v4.1.0, right?

**Comment by surrealzerg** [comment]
Yeah, 4.1.0 had doors opening.

**Comment by Saibot393** [comment]
There is only one reason for this behaviour, as far as i could find, though i am not sure how this would have changed for a specific door between v4.1.0 and v4.1.1. I have implemented a fix with v4.1.2 in case it truly is the reason. Should that not fix it, could you select the door-tile in question, put this into the console and sent me the out?
`canvas.tiles.controlled[0].document.flags.LocknKey`

**Comment by surrealzerg** [comment]
Here's the door tile.flags.LocknKey:
{
    "OpenImageFlag": "modules/levels-3d-preview/assets/blank.webp",
    "ClosedImageFlag": "modules/levels-3d-preview/assets/blank.webp",
    "LockableFlag": true,
    "LockedFlag": true,
    "IDKeysFlag": "plainKey",
    "UseKeyDialogFlag": true,
    "PasskeysFlag": "",
    "PasskeyChangeableFlag": false,
    "IdentityKeyFlag": "",
    "LockjammedFlag": false,
    "LockDCFlag": 15,
    "SpecialLPFlag": "Lockpick",
    "LockBreakDCFlag": 25,
    "currentLPsuccessFlag": 0,
    "requiredLPsuccessFlag": 1,
    "LPAttemptsFlag": 5,
    "LPAttemptsMaxFlag": 5,
    "canbeCircumventedFreeFlag": true,
    "SoundVariantFlag": "futuristic",
    "isOpenFlag": false,
    "CustomPopupsFlag": {
        "LockLocked": "It's locked",
        "LocknotPickable": "It can't be picked",
        "LocknotBreakable": "It can't be broken",
        "LockPasskeyTitle": "Enter password",
        "LocknotCustom": "",
        "CharacternotPickpocketable": ""
    }
}

Here's item.flags.LocknKey:

{
    "PickPocketDCFlag": "0",
    "IDKeysFlag": "plainKey",
    "RemoveKeyonUseFlag": false,
    "LPFormulaFlag": "",
    "LPFormulaOverrideFlag": false,
    "LBFormulaFlag": "",
    "LBFormulaOverrideFlag": false,
    "ReplacementItemFlag": ""
}

**Comment by Saibot393** [comment]
Could you try downgrading to v4.1.0 and see if that causes the door to work? If not, could you try to create a new door?

**Comment by Saibot393** [comment]
Also, which control sceme are you using on the player account?

**Comment by surrealzerg** [comment]
I've done some more testing and I'm seeing:
1) Most of the time I am not able to unlock the door using the standard control K. I was able to get it to work one time, but upon reloading the server 3 times, none of the subsequent loads would allow unlock. The below feedback is from the one time it did work.
2) It did not play an unlock sound, though an unlock sound was set. There is no way for the player to know a door is unlocked.
3) I received a "user does not have permission to update tile" error when the player opened the door after unlock. It still opened, just threw the notification error also.

Note:
Originally I assumed that just by trying to open the door by double clicking on it, the key would be used or a dialogue would show. In my test that only would happen when highlighting the door and pressing K.

**Comment by Saibot393** [comment]
I might have found the problem, i have released a fix with v4.1.5 (hopefully)

**Comment by Saibot393** [comment]
Just to make sure, the tab button shows up, but clicking on it does not change the tab, correct?
Have you tried running [find the culprit](https://foundryvtt.com/packages/find-the-culprit/)

**Comment by BRAYDIN72** [comment]
Working on it but so far it came up that 3d canvas or one of the base
modules is the culprit. Then the server crashed.

**Comment by Saibot393** [comment]
Which Foundry version is the server running?
